services:
  products:
    build: ./services/products
    container_name: products
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - backend-net

  inventory:
    build: ./services/inventory
    container_name: inventory
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      - products
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
